[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "8o9mJn2E4DFr5hGMqaF2Uh7bRJkx85KzFp9WyHwR3SGa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
